[package]
name = "gh-commit-race"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
tui-input = "0.11.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
chrono = "0.4.39"
ureq = "2.12.1"
